### ISSUE TITLE
Cannot pull dash image using rootless docker

### ISSUE THREAD

**Issue by HendrikSchrieber** [m9sweeper/m9sweeper#117]
Trying to pull the dash image using `docker pull ghcr.io/m9sweeper/dash:1.3.5` fails when running rootless docker:
```
$ docker pull ghcr.io/m9sweeper/dash:1.3.5
1.3.5: Pulling from m9sweeper/dash
f56be85fc22e: Already exists 
4e21e25411da: Pull complete 
9890dc0be345: Pull complete 
61d1890b04b0: Pull complete 
f45381a0d065: Pull complete 
640e7c28ec7b: Pull complete 
55d04ba527cb: Extracting  66.16MB/66.16MB
82f81d286bff: Download complete 
12c0946e17d7: Download complete 
8a406b2e38b4: Download complete 
b2f1887489a8: Download complete 
failed to register layer: failed to Lchown "/usr/src/app/node_modules/buffer-equal-constant-time/.npmignore" for UID 718322462, GID 454177323 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /usr/src/app/node_modules/buffer-equal-constant-time/.npmignore: invalid argument
```

Increasing the number of subordinate IDs as suggested in the error message does not help.

Not sure if this is an issue with rootless docker or the image itself so I cross-reported here: https://github.com/moby/moby/issues/45757

**Comment by jacobbeasley** [comment]
I wonder if we could maybe chown all of the files in node_modules to the same user during the docker step where we npm install so that the cardinality is reduced. Maybe the node_modules are getting marked owned by different users or something.

**Comment by corhere** [comment]
> Maybe the node_modules are getting marked owned by different users or something.

Yes, they are: see https://github.com/moby/moby/issues/45757#issuecomment-1613525964

**Comment by jacobbeasley** [comment]
I believe that Jon has a fix for this now that will be included in the next release - https://github.com/m9sweeper/m9sweeper/pull/134/files

**Comment by jacobbeasley** [comment]
This was resolved in our latest release. Thanks!
