### ISSUE TITLE
Could not get namespaces

### ISSUE THREAD

**Issue by tropnikovvl** [m9sweeper/m9sweeper#297]
Hi, I just installed your product and after rebooting the pod I get this error.

![Screenshot 2023-09-27 at 13 00 08](https://github.com/m9sweeper/m9sweeper/assets/76093012/9307d35d-fd7f-418e-90bb-bb60839f973e)

**Comment by becky-intelletive** [comment]
Were you able to make any progress on this error?
If not, check out your developer tools to see the API requests. Look for the following:
/api/kubesec/listnamespaces?cluster=(whatever your cluster id is)
Reply with the response please :)

**Comment by jacobbeasley** [comment]
Typically this means it can't talk to the kubernetes api (for wahtever reason). It installs and mounts a default service account's credentials and this has worked consistently for us, but if you check the dash pod's logs you might get more of a clue as to why the service account it installed with is not working in your environment.

**Comment by jacobbeasley** [comment]
Worst-case, you can "resync" it by navigating to your cluster, clicking cluster info tab on the left, and then clicking "Update Kubeconfig" at the top. That wizard will walk you through re-installing the service account in your cluster.
