### ISSUE TITLE
Can't pull images from GCR private registry

### ISSUE THREAD

**Issue by sarath-s-kumar** [m9sweeper/m9sweeper#78]
Docker Daemon Running?
* Unable To Initialize Podman Client: No Podman Socket Found: Stat Podman/Podman.Sock: No Such File Or Directory
* GET Https://Asia.Gcr.Io/V2/project-name/application/Manifests/V0.0.2-Dd7e-DEV-SNAPSHOT: UNAUTHORIZED: You Don't Have The Needed Permissions To Perform This Operation, And You May Have Invalid Credentials. To Authenticate Your Request, Follow The Steps In: Https://Cloud.Google.Com/Container-Registry/Docs/Advanced-Authentication

I created a service account json in gcr hosted gcp project and uploaded the json in the m9sweeper dashboard registry.

**Comment by sarath-s-kumar** [comment]
I am able to see we don't have any code written for authenticating gcr in our trivy scanner codebase.

**Comment by jacobbeasley** [comment]
@sarath-s-kumar  I believe you can fix this if you go to the UI and setup GCR and its credentials there.

**Comment by sarath-s-kumar** [comment]
I already did through theUI but in the backend java file for trivy scanning we are not authenticating GCR. Then how it is possible to use that credentials.

**Comment by jacobbeasley** [comment]
@SahilNarans I know you have done this before. I believe they had to put in a Google API Key of some kind as the password. Maybe we can elaborate in the README files.

**Comment by SahilNarans** [comment]
Hi @sarath-s-kumar  Have you added registry credentials with helm upgrade command as environment variable ?
If no, Please try to run helm upgrade command and add repo details like below mentioned variables.

    --set-string 'dash.init.docker.registries[1]'.name=test \
    --set-string 'dash.init.docker.registries[1]'.hostname=test.io \
    --set-string 'dash.init.docker.registries[1]'.login_required=true \
    --set-string 'dash.init.docker.registries[1]'.username=abc \
    --set-string 'dash.init.docker.registries[1]'.password=abc \
    
    Let me know, if you have any query.

**Comment by sarath-s-kumar** [comment]
I already passed my service account json for gcr using with this helm upgrade command but it won't work . My doubt is how this JSON parsed to the trivy scanner in backend. In the scanner code we are not mentioning any authentication for GCR it only validates for Amazon only.

**Comment by jacobbeasley** [comment]
https://github.com/m9sweeper/m9sweeper/blob/main/trawler/src/main/java/io/m9sweeper/trawler/scanners/Trivy.java#L104 - looks like we didn't quite finish setting up the GCR integration in Trawler. 

https://aquasecurity.github.io/trivy/v0.39/docs/advanced/private-registries/gcr/

We created the UI/Fields for it, but never finished implementing in Trivy. I tried using basic auth but found that it was not working for me (see error below), but we can see about finishing this feature and getting it working in the next release. 

![image](https://user-images.githubusercontent.com/433581/230211973-b1ccbd88-fef4-4f8e-ba1c-6c0399bc0111.png)

**Comment by jacobbeasley** [comment]
You can see it in the UI here - 

![image](https://user-images.githubusercontent.com/433581/230212230-93fd36e3-bb2c-496f-b1c5-2b7d21378468.png)

**Comment by brandan-schmitz** [comment]
@sarath-s-kumar this has been fixed and should be included in a release tomorrow sometime.

**Comment by jacobbeasley** [comment]
@sarath-s-kumar  Release 1.3.1 is out now and it should work now! You have to use the JSON Key File method documented here with M9sweeper. 

Thanks guys for digging in and getting this working! 

https://cloud.google.com/container-registry/docs/advanced-authentication
